name: FakePlayerPlugin
main: com.tuplugin.FakePlayerPlugin
version: 1.0
api-version: 1.21
commands:
  npcspawn:
    description: Spawnea un fake player con skin y nombre
    usage: /npcspawn <nombre> [skin]
