name: Build Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install ProtocolLib in local Maven
        run: |
          mvn install:install-file \
            -Dfile=libs/ProtocolLib.jar \
            -DgroupId=com.comphenix.protocol \
            -DartifactId=ProtocolLib \
            -Dversion=5.3.0 \
            -Dpackaging=jar

      - name: Download AuthLib
        run: wget -O authlib-3.4.1.jar https://repo1.maven.org/maven2/com/mojang/authlib/3.4.1/authlib-3.4.1.jar

      - name: Install AuthLib in local Maven
        run: |
          mvn install:install-file \
            -Dfile=authlib-3.4.1.jar \
            -DgroupId=com.mojang \
            -DartifactId=authlib \
            -Dversion=3.4.1 \
            -Dpackaging=jar

      - name: Build with Maven
        run: mvn clean package

      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: FakePlayerPlugin
          path: target/*.jar
